In [1]:
!pip3 install nba-api

Requirement already satisfied: nba-api in /home/harshvardhan/Documents/NBA PREDICTION/nba-prediction/venv/lib/python3.8/site-packages (1.1.9)
Requirement already satisfied: requests in /home/harshvardhan/Documents/NBA PREDICTION/nba-prediction/venv/lib/python3.8/site-packages (from nba-api) (2.22.0)

In [9]:
from nba_api.stats.static import teams
from nba_api.stats.library.parameters import SeasonAll
import pandas as pd 
from nba_api.stats.endpoints import leaguegamefinder

In [13]:
teams = teams.get_teams()
GSW = [x for x in teams if x['full_name'] == 'Golden State Warriors'][0]
GSW_id = GSW['id']

In [14]:
GSW_games = leaguegamefinder.LeagueGameFinder(team_id_nullable=GSW_id).get_data_frames()[0]

In [22]:
GSW_games[GSW_games['SEASON_ID']=='22018']
GSW_games.columns
GSW_games.drop(columns=['SEASON_ID','TEAM_ID','TEAM_NAME','GAME_DATE'])

,TEAM_ABBREVIATION,GAME_ID,MATCHUP,WL,MIN,PTS,FGM,FGA,FG_PCT,FG3M,...,FT_PCT,OREB,DREB,REB,AST,STL,BLK,TOV,PF,PLUS_MINUS
0,GSW,0021900967,GSW vs. LAC,L,239,107,37,79,0.468,11,...,0.815,4.0,31.0,35.0,25,3,0,9,17,-24.0
1,GSW,0021900944,GSW vs. PHI,W,240,118,44,80,0.550,9,...,0.750,7.0,28.0,35.0,30,4,2,7,19,4.0
2,GSW,0021900929,GSW vs. TOR,L,240,113,40,98,0.408,14,...,0.760,14.0,38.0,52.0,34,4,5,15,23,-8.0
3,GSW,0021900913,GSW @ DEN,W,239,116,42,82,0.512,18,...,0.636,5.0,30.0,35.0,31,8,3,11,23,16.0
4,GSW,0021900901,GSW vs. WAS,L,239,110,42,89,0.472,9,...,0.708,18.0,34.0,52.0,25,7,7,21,24,-14.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
3303,GOS,0028300048,GOS vs. NYK,W,240,102,35,92,0.380,0,...,0.711,25.0,18.0,43.0,20,16,4,17,27,NaN
3304,GOS,0028300040,GOS @ UTH,L,240,112,44,115,0.383,2,...,0.880,27.0,26.0,53.0,22,11,4,19,31,NaN
3305,GOS,0028300029,GOS @ KCK,L,240,114,42,91,0.462,0,...,0.750,12.0,18.0,30.0,29,15,3,16,28,NaN
3306,GOS,0028300013,GOS vs. POR,W,240,97,34,76,0.447,0,...,0.725,12.0,31.0,43.0,21,9,1,16,37,NaN
3307,GOS,0028300004,GOS @ SEA,W,240,110,42,89,0.472,0,...,0.703,21.0,26.0,47.0,26,11,2,19,34,NaN

In [23]:
frames=[]
for team in teams:
    tid=team['id']
    df=leaguegamefinder.LeagueGameFinder(team_id_nullable=tid).get_data_frames()[0]
    df=df[df['SEASON_ID']=='22018']
    df=df.drop(columns=['SEASON_ID','TEAM_ID','TEAM_NAME','GAME_DATE'])
    frames.append(df)

In [25]:
len(frames)

30

In [26]:
df=pd.concat(frames)

In [28]:
df=df.drop(columns=['SEASON_ID','TEAM_ID','TEAM_NAME','GAME_DATE'])

In [33]:
df.columns

Index(['TEAM_ABBREVIATION', 'GAME_ID', 'MATCHUP', 'WL', 'MIN', 'PTS', 'FGM',
       'FGA', 'FG_PCT', 'FG3M', 'FG3A', 'FG3_PCT', 'FTM', 'FTA', 'FT_PCT',
       'OREB', 'DREB', 'REB', 'AST', 'STL', 'BLK', 'TOV', 'PF', 'PLUS_MINUS'],
      dtype='object')

In [39]:
df[df['WL']=='W']['TEAM_ABBREVIATION'].value_counts()

MIL    62
GSW    61
TOR    60
POR    60
DEN    57
HOU    57
UTA    54
BOS    53
PHI    53
OKC    52
SAS    51
IND    50
LAC    50
DET    44
ORL    44
LAL    43
MIA    43
CHA    42
SAC    42
BKN    42
MEM    39
MIN    39
DAL    36
NOP    35
WAS    33
ATL    32
CHI    24
CLE    24
PHX    23
NYK    19
Name: TEAM_ABBREVIATION, dtype: int64

In [40]:
df.to_csv('nba_games_data_using_.csv', index=False)